/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import MODEL.Students;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thien
 */
public class frmQuanLyDiem extends javax.swing.JFrame {

    /**
     * Creates new form frmQuanLyDiem
     */
    public frmQuanLyDiem() {
        initComponents();
        HienThiDS();
    }
    public void HienThiDS()
    {
      Vector<Students> ds = new Vector<Students>();
    int ketqua = DAO.tblStudents.LayDSSinhVien(ds);
    if (ketqua == -1 || ketqua == -2) {
        JOptionPane.showMessageDialog(this, "Lỗi SQL");
        return;
    } else {
        DefaultTableModel dtm = (DefaultTableModel) this.tblSinhVien.getModel();
        dtm.setRowCount(0);
        for (Students dss : ds) {
            
            dtm.addRow(new Object[]{dss.getMasv(), dss.getHoten(), dss.getTiengAnh(), dss.getTinHoc(), dss.getGdtc(), dss.tinhDiemTrungBinh()});
        }
    }
    }
    private float tinhDiemTrungBinh(float diemTA, float diemTH, float diemGDTC) {
    return (diemTA + diemTH + diemGDTC) / 3;
}
    private int currentIndex = 0;
    private void displayRecord() {
    DefaultTableModel model = (DefaultTableModel) tblSinhVien.getModel();
    if (model.getRowCount() > 0) {
        // Get the data from the current record based on the currentIndex
        String masv = model.getValueAt(currentIndex, 0).toString();
        String hoten = model.getValueAt(currentIndex, 1).toString();
        float tienganh = Float.parseFloat(model.getValueAt(currentIndex, 2).toString());
        float tinhoc = Float.parseFloat(model.getValueAt(currentIndex, 3).toString());
        float gdct = Float.parseFloat(model.getValueAt(currentIndex, 4).toString());
        float diemTB = tinhDiemTrungBinh(tienganh,tinhoc,gdct) ;
        // Display the data in the appropriate UI components
        txtMaSV.setText(masv);
        txtHoTen.setText(hoten);
        txtTiengAnh.setText(String.valueOf(tienganh));
        txtTinHoc.setText(String.valueOf(tinhoc));
        txtGDTC.setText(String.valueOf(gdct));
        lblDiemTB.setText(String.valueOf(diemTB));
    }
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTiengAnh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTinHoc = new javax.swing.JTextField();
        txtGDTC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblDiemTB = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSinhVien = new javax.swing.JTable();
        btnMaxDiem = new javax.swing.JButton();
        btnDau = new javax.swing.JButton();
        btnSau = new javax.swing.JButton();
        btnTruoc = new javax.swing.JButton();
        btnCuoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("QUAN LY DIEM SINH VIEN");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tim Kiem"));

        jLabel2.setText("MaSV");

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jLabel3.setText("HoTen :");

        txtHoTen.setForeground(new java.awt.Color(51, 51, 255));

        jLabel5.setText("MaSV");

        jLabel6.setText("Tieng Anh");

        jLabel7.setText("Tin Hoc");

        jLabel8.setText("Giao Duc");

        jLabel9.setText("Diem TB:");

        lblDiemTB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDiemTB.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblDiemTB, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaSV)
                            .addComponent(txtTiengAnh)
                            .addComponent(txtTinHoc)
                            .addComponent(txtGDTC, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTiengAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTinHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtGDTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Add.png"))); // NOI18N
        btnThem.setText("NEW");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save.png"))); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Delete.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Edit.png"))); // NOI18N
        btnSua.setText("UPDATE");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        tblSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MASV", "HOTEN", "TIENGANH", "TINHOC", "GDTC", "DIEMTB"
            }
        ));
        tblSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSinhVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSinhVien);

        btnMaxDiem.setText("Max");
        btnMaxDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaxDiemActionPerformed(evt);
            }
        });

        btnDau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/rewind.png"))); // NOI18N
        btnDau.setText("<<");
        btnDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDauActionPerformed(evt);
            }
        });

        btnSau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fast_forward.png"))); // NOI18N
        btnSau.setText(">");
        btnSau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSauActionPerformed(evt);
            }
        });

        btnTruoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/skip_backward.png"))); // NOI18N
        btnTruoc.setText("<");
        btnTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruocActionPerformed(evt);
            }
        });

        btnCuoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fast_forward.png"))); // NOI18N
        btnCuoi.setText(">>");
        btnCuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(132, 132, 132)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(20, 20, 20))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnThem)
                                .addComponent(btnSave)
                                .addComponent(btnDelete)
                                .addComponent(btnSua)
                                .addComponent(btnMaxDiem))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btnDau)
                        .addGap(18, 18, 18)
                        .addComponent(btnSau, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCuoi)))
                .addContainerGap(391, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMaxDiem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDau)
                    .addComponent(btnSau)
                    .addComponent(btnTruoc)
                    .addComponent(btnCuoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
         // Lấy thông tin từ các trường nhập liệu
    String maSV = txtMaSV.getText();
    String hoTen = txtHoTen.getText();
    float diemTA, diemTH, diemGDTC;
    try {
        diemTA = Float.parseFloat(txtTiengAnh.getText());
        diemTH = Float.parseFloat(txtTinHoc.getText());
        diemGDTC = Float.parseFloat(txtGDTC.getText());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Điểm phải là một số.");
        return;
    }

    // Kiểm tra xem các trường nhập liệu có bị bỏ trống không
    if (maSV.isEmpty() || hoTen.isEmpty() || txtTiengAnh.getText().isEmpty() || txtTinHoc.getText().isEmpty() || txtGDTC.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin.");
        return;
    }
    
    // Gọi phương thức ThemSinhVien từ lớp DAO.tblStudents để thêm sinh viên vào CSDL
    int addResult = DAO.tblStudents.ThemSinhVien(maSV, hoTen, diemTA, diemTH, diemGDTC);
    
    // Kiểm tra kết quả thêm sinh viên và hiển thị thông báo tương ứng
    if (addResult > 0) {
        JOptionPane.showMessageDialog(this, "Thêm sinh viên thành công.");
         HienThiDS();
        // Cập nhật hiển thị danh sách sinh viên hoặc làm bất kỳ công việc nào khác cần thiết ở đây
    } else {
        JOptionPane.showMessageDialog(this, "Thêm sinh viên thất bại. Vui lòng kiểm tra lại thông tin.");
    }
         
         
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblSinhVien.getSelectedRow();
    if (selectedRow >= 0) {
        String maSV = tblSinhVien.getValueAt(selectedRow, 0).toString();
        
        // Confirm deletion
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa sinh viên này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            int deleteResult = DAO.tblStudents.XoaSinhVien(maSV);
            
            if (deleteResult > 0) {
                JOptionPane.showMessageDialog(this, "Xóa sinh viên thành công.");
                HienThiDS(); // Refresh the display of student list
            } else if (deleteResult == -1) {
                JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu.");
            } else {
                JOptionPane.showMessageDialog(this, "Xóa sinh viên thất bại. Vui lòng kiểm tra lại.");
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên cần xóa.");
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSinhVienMouseClicked
       int selectedRow = tblSinhVien.getSelectedRow();
    if (selectedRow >= 0) {
        String maSV = tblSinhVien.getValueAt(selectedRow, 0).toString();
        String hoTen = tblSinhVien.getValueAt(selectedRow, 1).toString();
        float diemTA = Float.parseFloat(tblSinhVien.getValueAt(selectedRow, 2).toString());
        float diemTH = Float.parseFloat(tblSinhVien.getValueAt(selectedRow, 3).toString());
        float diemGDTC = Float.parseFloat(tblSinhVien.getValueAt(selectedRow, 4).toString());
        
        txtMaSV.setText(maSV);
        txtHoTen.setText(hoTen);
        txtTiengAnh.setText(String.valueOf(diemTA));
        txtTinHoc.setText(String.valueOf(diemTH));
        txtGDTC.setText(String.valueOf(diemGDTC));
        
         float diemTB = tinhDiemTrungBinh(diemTA, diemTH, diemGDTC);
        lblDiemTB.setText(String.format("%.2f", diemTB));
    }
    }//GEN-LAST:event_tblSinhVienMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
         JFileChooser fileChooser = new JFileChooser();
    int result = fileChooser.showSaveDialog(this);
    
    if (result == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
       
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
            // Ghi dữ liệu vào file
            // Ví dụ: Ghi dữ liệu từ bảng tblSinhVien vào file
            
            for (int row = 0; row < tblSinhVien.getRowCount(); row++) {
                for (int column = 0; column < tblSinhVien.getColumnCount(); column++) {
                    Object value = tblSinhVien.getValueAt(row, column);
                    writer.write(value.toString());
                    
                    if (column < tblSinhVien.getColumnCount() - 1) {
                        writer.write(", "); // Phân tách giữa các cột
                    }
                }
                
                writer.newLine(); // Xuống dòng sau mỗi dòng
            }
            
            JOptionPane.showMessageDialog(this, "FIle Luu thanh cong roi do.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Loi roi : " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        // Lấy thông tin từ các trường nhập liệu
    String maSV = txtMaSV.getText();
    String hoTen = txtHoTen.getText();
    float diemTA, diemTH, diemGDTC;
    try {
        diemTA = Float.parseFloat(txtTiengAnh.getText());
        diemTH = Float.parseFloat(txtTinHoc.getText());
        diemGDTC = Float.parseFloat(txtGDTC.getText());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Điểm phải là một số.");
        return;
    }

    // Kiểm tra xem các trường nhập liệu có bị bỏ trống không
    if (maSV.isEmpty() || hoTen.isEmpty() || txtTiengAnh.getText().isEmpty() || txtTinHoc.getText().isEmpty() || txtGDTC.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin.");
        return;
    }

    // Gọi phương thức SuaSinhVien từ lớp DAO.tblStudents để cập nhật sinh viên trong CSDL
    int updateResult = DAO.tblStudents.SuaSinhVien(maSV, hoTen, diemTA, diemTH, diemGDTC);

    // Kiểm tra kết quả cập nhật sinh viên và hiển thị thông báo tương ứng
    if (updateResult > 0) {
        JOptionPane.showMessageDialog(this, "Cập nhật sinh viên thành công.");
        HienThiDS(); // Refresh the display of the student list
    } else if (updateResult == -1) {
        JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu.");
    } else {
        JOptionPane.showMessageDialog(this, "Cập nhật sinh viên thất bại. Vui lòng kiểm tra lại thông tin.");
    }
        
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
            // Lấy từ khóa tìm kiếm từ trường nhập liệu
    String masv = txtSearch.getText();

    // Gọi phương thức TimSinhVienTheoMASV từ lớp DAO.tblStudents để tìm sinh viên theo MASV
    Students student = DAO.tblStudents.TimSinhVienTheoMASV(masv);

    // Kiểm tra kết quả tìm kiếm và cập nhật bảng hiển thị
    if (student != null) {
        DefaultTableModel model = (DefaultTableModel) tblSinhVien.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ trong bảng

        Object[] row = new Object[6];
        row[0] = student.getMasv();
        row[1] = student.getHoten();
        row[2] = student.getTiengAnh();
        row[3] = student.getTinHoc();
        row[4] = student.getGdtc();
        row[5] = student.tinhDiemTrungBinh() ;
        model.addRow(row);
    } else {
        JOptionPane.showMessageDialog(this, "Không tìm thấy sinh viên nào.");
    }

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnMaxDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaxDiemActionPerformed
         // Call the function to retrieve the top three students with highest average scores
    Vector<Students> topStudents = DAO.tblStudents.LayTop3SinhVienDiemTBCaoNhat();

    // Clear the existing data from the tblSinhVien table
    DefaultTableModel model = (DefaultTableModel) tblSinhVien.getModel();
    model.setRowCount(0);

    // Populate the tblSinhVien table with the retrieved data
    for (Students student : topStudents) {
        Object[] row = {
            student.getMasv(),
            student.getHoten(),
            student.getTiengAnh(),
            student.getTinHoc(),
            student.getGdtc(),
            student.tinhDiemTrungBinh() 
        };
        model.addRow(row);
    }
    }//GEN-LAST:event_btnMaxDiemActionPerformed

    private void btnDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDauActionPerformed
        // TODO add your handling code here:
        currentIndex = 0; // Set the index to the first record
    displayRecord();
    }//GEN-LAST:event_btnDauActionPerformed

    private void btnSauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSauActionPerformed
        // TODO add your handling code here:
         if (currentIndex < tblSinhVien.getRowCount() - 1) {
        currentIndex++; // Increment the index to move to the next record
        displayRecord();
    }
    }//GEN-LAST:event_btnSauActionPerformed

    private void btnTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruocActionPerformed
        // TODO add your handling code here:
         if (currentIndex > 0) {
        currentIndex--; // Decrement the index to move to the previous record
        displayRecord();
    }
    }//GEN-LAST:event_btnTruocActionPerformed

    private void btnCuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuoiActionPerformed
        // TODO add your handling code here:currentIndex = tblSinhVien.getRowCount() - 1; // Set the index to the last record
    currentIndex = tblSinhVien.getRowCount() - 1; // Set the index to the last record
    displayRecord();
    }//GEN-LAST:event_btnCuoiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQuanLyDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQuanLyDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQuanLyDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQuanLyDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQuanLyDiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCuoi;
    private javax.swing.JButton btnDau;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnMaxDiem;
    private javax.swing.JButton btnSau;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTruoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiemTB;
    private javax.swing.JTable tblSinhVien;
    private javax.swing.JTextField txtGDTC;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTiengAnh;
    private javax.swing.JTextField txtTinHoc;
    // End of variables declaration//GEN-END:variables
}
